apiVersion: build.platformspec.io/v1alpha1
kind: Cluster
metadata:
  name: dev-cluster-aws-fargate
spec:
  providerRefs:
    - kind: Provider
      name: aws
    - kind: Provider
      name: aws-fargate
  environmentRef:
    name: development
  version: "1.4.0"
  region: us-east-2
  config: {}
